include $(GNUSTEP_MAKEFILES)/common.make
APP_NAME = Note 
Note_HEADERS = TestProtocol.h ProtocolFromNet.h TestProtocolProxy-testCategory.h TestExtension.h TestID.h\
	TestProperty.h TestNSClass.h
Note_OBJC_FILES = main.m TestProtocol.m ProtocolFromNet.m TestProtocolProxy-testCategory.m TestExtension.m TestID.m\
	TestProperty.m  TestNSClass.m
Note_RESOURCE_FILES = 
include $(GNUSTEP_MAKEFILES)/application.make

