#ifndef GLODONMODELVIEW_GLOBAL_H
#define GLODONMODELVIEW_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(GLODONMODELVIEW_LIBRARY)
#  define GLODONMODELVIEWSHARED_EXPORT Q_DECL_EXPORT
#else
#  define GLODONMODELVIEWSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // GLODONMODELVIEW_GLOBAL_H
