include $(GNUSTEP_MAKEFILES)/common.make
APP_NAME = HelloWorld
HelloWorld_HEADERS = Cattle.h Bull.h DoProxy.h
HelloWorld_OBJC_FILES = main.m Cattle.m Bull.m DoProxy.m
HelloWorld_RESOURCE_FILES =
include $(GNUSTEP_MAKEFILES)/application.make

