#ifndef GLODONLEARN_GLOBAL_H
#define GLODONLEARN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(GLODONLEARN_LIBRARY)
#  define GLODONLEARNSHARED_EXPORT Q_DECL_EXPORT
#else
#  define GLODONLEARNSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // GLODONLEARN_GLOBAL_H
