#ifndef GLODONPATTERN_GLOBAL_H
#define GLODONPATTERN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(GLODONPATTERN_LIBRARY)
#  define GLODONPATTERNSHARED_EXPORT Q_DECL_EXPORT
#else
#  define GLODONPATTERNSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // GLODONPATTERN_GLOBAL_H
